--  Template for database `Genomes` (updated 10-3-14 JPD)
--
--  1) Table structure for table `xGDB_Log`
--

DROP TABLE IF EXISTS `xGDB_Log`;
CREATE TABLE `xGDB_Log` (
  `ID` int(6) NOT NULL AUTO_INCREMENT,
  `DBname` varchar(150) DEFAULT '',
  `Organism` varchar(50) DEFAULT '',
  `Common_Name` varchar(50) DEFAULT '',
  `Create_Date` varchar(50) DEFAULT '',
  `Config_Date` varchar(50) DEFAULT '',
  `Input_Data_Path` varchar(100) DEFAULT '',
  `Status` varchar(20) DEFAULT '',
  `Process_Type` varchar(20) NOT NULL default '',
  `Genome_Type` varchar(50) DEFAULT '',
  `Genome_Source` varchar(50) DEFAULT '',
  `Genome_Source_Link` varchar(100) DEFAULT '',
  `Genome_Comments` mediumtext,
  `Genome_Version` varchar(60) DEFAULT '',
  `Genome_Count` int(11) DEFAULT NULL,
  `Chromosome_Count` int(11) DEFAULT NULL,
  `Unlinked_Chromosome_Count` int(11) DEFAULT NULL,
  `Scaffold_Count` int(11) DEFAULT NULL,
  `BAC_Count` int(11) DEFAULT NULL,
  `GeneModel_Version` varchar(60) DEFAULT '',
  `GeneModel_Source` varchar(50) DEFAULT '',
  `GeneModel_Link` varchar(200) DEFAULT '',
  `GeneModel_Comments` mediumtext,
  `EST_Align_sp` varchar(50) DEFAULT '',
  `EST_Align_Version` varchar(60) DEFAULT '',
  `EST_Align_Comments` mediumtext,
  `cDNA_Align_sp` varchar(50) DEFAULT '',
  `cDNA_Align_Version` varchar(60) DEFAULT '',
  `cDNA_Align_Comments` mediumtext,
  `PUT_Align_sp` varchar(50) DEFAULT '',
  `PUT_Align_Version` varchar(10) DEFAULT '',
  `PUT_Align_Comments` mediumtext,
  `Prot_Align_sp` varchar(50) DEFAULT '',
  `Prot_Align_Comments` text,
  `Prot_Align_Version` varchar(20) DEFAULT '',
  `Default_GSEG` varchar(200) DEFAULT '',
  `Default_lpos` varchar(20) DEFAULT '',
  `Default_rpos` varchar(20) DEFAULT '',
  `yrGATE_Reference` varchar(20) DEFAULT '',
  `yrGATE_Admin_Email` varchar(200) DEFAULT '',
  `GFF_Type` varchar(50) DEFAULT '',
  `Update_Status` varchar(20) DEFAULT '',
  `Update_Data_Path` varchar(100) DEFAULT '',
  `Update_Data_EST` varchar(20) DEFAULT '',
  `Update_Data_cDNA` varchar(20) DEFAULT '',
  `Update_Data_TrAssembly` varchar(20) DEFAULT '',
  `Update_Data_Protein` varchar(20) DEFAULT '',
  `Update_Data_GSEG` varchar(20) DEFAULT '',
  `Update_Data_GeneModel` varchar(20) DEFAULT '',
  `Update_Data_CpGATModel` varchar(20) DEFAULT '',
  `Update_Descriptions` varchar(20) DEFAULT '',
  `Update_Date` varchar(50) DEFAULT '',
  `Species_Model` varchar(20) DEFAULT '',
  `Alignment_Stringency` varchar(20) DEFAULT '',
  `Update_Comments` mediumtext,
  `Update_History` mediumtext,
  `CpGAT_Status` varchar(20) DEFAULT '',
  `CpGAT_ReferenceProt_File` varchar(100) DEFAULT '',
  `RepeatMask_File` varchar(100) DEFAULT '',
  `CpGAT_BGF` varchar(20) DEFAULT '',
  `CpGAT_Augustus` varchar(20) DEFAULT '',
  `CpGAT_GeneMark` varchar(20) DEFAULT '',
  `CpGAT_Skip_Mask` varchar(20) DEFAULT '',
  `CpGAT_Relax_UniRef` varchar(20) DEFAULT '',
  `CpGAT_Skip_PASA` varchar(20) DEFAULT '',
  `CpGAT_Filter_Genes` varchar(20) DEFAULT '',
  `Update_Data_CpGAT` varchar(20) DEFAULT '',
  `Gth_Species_Model` varchar(20) DEFAULT '',
  `Archive_Date` varchar(50) DEFAULT '',
  `Archive_File` varchar(200) DEFAULT '',
  `Restore_Date` varchar(50) DEFAULT '',
  `Restore_From_File` varchar(200) DEFAULT '',
  `RepeatMask_Status` varchar(20) DEFAULT '',
  `GSQ_CompResources` varchar(20) DEFAULT '',
  `GSQ_Job_EST` varchar(50) DEFAULT '',
  `GSQ_Job_EST_Result` varchar(500) DEFAULT '',
  `GSQ_Job_cDNA` varchar(50) DEFAULT '',
  `GSQ_Job_cDNA_Result` varchar(500) DEFAULT '',
  `GSQ_Job_PUT` varchar(50) DEFAULT '',
  `GSQ_Job_PUT_Result` varchar(500) DEFAULT '',
  `GTH_CompResources` varchar(20) DEFAULT '',
  `GTH_Job` varchar(50) DEFAULT '',
  `GTH_Job_Result` varchar(500) DEFAULT '',
  `Archive_All_Date` varchar(50) default '',
  `Restore_All_Date` varchar(50) default '',
  `Create_History` mediumtext,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
--  2) Table structure for table `Datafiles`
--

DROP TABLE IF EXISTS `Datafiles`;
CREATE TABLE `Datafiles` (
  `uid` int(6) NOT NULL AUTO_INCREMENT,
  `Valid` varchar(1) DEFAULT '',
  `UserFile` varchar(1) DEFAULT '',
  `ValidationTimeStamp` varchar(100) DEFAULT NULL,
  `FileName` varchar(150) DEFAULT '',
  `Path` varchar(150) DEFAULT '',
  `FileStamp` varchar(10000) DEFAULT '',
  `FileSize` int(11) DEFAULT NULL,
  `SeqType` varchar(50) DEFAULT '',
  `SeqTypeCount` int(11) DEFAULT NULL,
  `Format` varchar(50) DEFAULT '',
  `Track` varchar(50) DEFAULT '',
  `EntryCount` int(11) DEFAULT NULL,
  `SizeTotal` int(11) DEFAULT NULL,
  `SizeAverage` int(11) DEFAULT NULL,
  `SizeMedian` int(11) DEFAULT NULL,
  `SizeSmallest` int(11) DEFAULT NULL,
  `SizeLargest` varchar(50) DEFAULT '',
  `Size2` int(11) DEFAULT NULL,
  `Size3` int(11) DEFAULT NULL,
  `Size4` int(11) DEFAULT NULL,
  `Size5` int(11) DEFAULT NULL,
  `Size6` int(11) DEFAULT NULL,
  `Size7` int(11) DEFAULT NULL,
  `Size8` int(11) DEFAULT NULL,
  `Size9` int(11) DEFAULT NULL,
  `Size10` int(11) DEFAULT NULL,
  `Size11` int(11) DEFAULT NULL,
  `Size12` int(11) DEFAULT NULL,
  `Size13` int(11) DEFAULT NULL,
  `Size14` int(11) DEFAULT NULL,
  `Size15` int(11) DEFAULT NULL,
  `Size16` int(11) DEFAULT NULL,
  `Size17` int(11) DEFAULT NULL,
  `Size18` int(11) DEFAULT NULL,
  `Size19` int(11) DEFAULT NULL,
  `Size20` int(11) DEFAULT NULL,
  `Size21` int(11) DEFAULT NULL,
  `Size22` int(11) DEFAULT NULL,
  `Size23` int(11) DEFAULT NULL,
  `Size24` int(11) DEFAULT NULL,
  `HardMaskN` int(11) DEFAULT '0',
  `HardMaskX` int(11) DEFAULT '0',
  `FastaValid` varchar(50) DEFAULT '',
  `DeflineTabs` int(11) DEFAULT '0',
  `FastaValidateMessage` varchar(500) DEFAULT NULL,
  `FastaDefline` varchar(500) DEFAULT '',
  `SampleContents` varchar(500) DEFAULT '',
  `Duplicates` varchar(50) DEFAULT '',
  `Unit` varchar(50) DEFAULT '',
  `Genes` int(11) DEFAULT NULL,
  `Transcripts` int(11) DEFAULT NULL,
  `Entries` int(11) DEFAULT NULL,
  `GSQAlignments` int(11) DEFAULT NULL,
  `GTHAlignments` int(11) DEFAULT NULL,
  PRIMARY KEY (`uid`),
  FULLTEXT KEY `filestamp` (`FileStamp`),
  FULLTEXT KEY `ValidationTimeStamp` (`ValidationTimeStamp`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
--  3) Table structure for table `Processes`
--

DROP TABLE IF EXISTS `Processes`;
CREATE TABLE `Processes` (
  `ProcessID` int(6) NOT NULL AUTO_INCREMENT,
  `ProcessTimeStamp` varchar(100) NOT NULL DEFAULT '',
  `ParentProcessTimeStamp` varchar(100) NOT NULL DEFAULT '',
  `ValidationTimeStamp` varchar(100) NOT NULL DEFAULT '',
  `GDB` varchar(20) NOT NULL DEFAULT '',
  `ProcessType` varchar(20) NOT NULL DEFAULT '',
  `Outcome` varchar(20) NOT NULL DEFAULT '',
  `Duration` int(9) DEFAULT NULL,
  UNIQUE KEY `ProcessIDIndex` (`ProcessID`),
  FULLTEXT KEY `ProcessTimeStampIndex` (`ProcessTimeStamp`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
--  4) Table structure for table `Validation`
--

DROP TABLE IF EXISTS `Validation`;
CREATE TABLE `Validation` (
  `uid` int(6) NOT NULL AUTO_INCREMENT,
  `FileStamp` varchar(10000) NOT NULL DEFAULT '',
  `ValidationTimestamp` varchar(100) NOT NULL DEFAULT '',
  UNIQUE KEY `uid` (`uid`),
  FULLTEXT KEY `FileStampIndex` (`FileStamp`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
