#!/bin/bash
while true; do
  echo ""; read -p "Update xGDBvm code?  [yn]:  " yn
    case $yn in
           [Yy]* )
           sudo svn update /xGDBvm/; 
            echo ""
              echo "The code has been updated from the Subversion repository."
            echo ""
           break;; 
           [Nn]* ) exit;;
           * ) echo "Please answer y or n.";;
    esac
done
